package org.dubh.islay.hub.model;

import javax.persistence.Id;

import com.google.common.base.Objects;

/**
 * Information about a user of the hub.
 * 
 * @author brianduff
 */
public class User {
  /**
   * The numeric internal identifier of this user. This is automatically
   * generated by AppEngine for persisted entities.
   */
  private @Id Long internalId;
  
  /**
   * The user visible identifier of this user. An openid or an email address.
   */
  private String userId;
  
  public Long getInternalId() {
    return internalId;
  }

  public User setInternalId(Long internalId) {
    this.internalId = internalId;
    return this;
  }

  public String getUserId() {
    return userId;
  }

  public User setUserId(String userId) {
    this.userId = userId;
    return this;
  }
  
  @Override
  public boolean equals(Object o) {
    if (o == this) return true;
    if (!(o instanceof User)) return false;
    User other = (User) o;
    return Objects.equal(internalId, other.internalId)
        && Objects.equal(userId, other.userId);
  }
  
  @Override
  public int hashCode() {
    return Objects.hashCode(internalId);
  }
}
